Repository boostcampwm-2024/web37-cloud-canvas, pull requests merged in 2024-11, with the labels that each got.

#23 NCloud SDK - VPC 마이그레이션
  packages/ncloud-sdk/src/services/vpc/VpcApi.ts
  packages/ncloud-sdk/src/services/vpc/models/CommonCode.ts
  packages/ncloud-sdk/src/services/vpc/models/CommonResponse.ts
  packages/ncloud-sdk/src/services/vpc/models/CreateVpcRequest.ts
  packages/ncloud-sdk/src/services/vpc/models/CreateVpcResponse.ts
  packages/ncloud-sdk/src/services/vpc/models/DeleteVpcRequest.ts
  packages/ncloud-sdk/src/services/vpc/models/DeleteVpcResponse.ts
  packages/ncloud-sdk/src/services/vpc/models/GetVpcDetailRequest.ts
  packages/ncloud-sdk/src/services/vpc/models/GetVpcDetailResponse.ts
  packages/ncloud-sdk/src/services/vpc/models/GetVpcListRequest.ts
  packages/ncloud-sdk/src/services/vpc/models/GetVpcListResponse.ts
  packages/ncloud-sdk/src/services/vpc/models/Vpc.ts
  packages/ncloud-sdk/src/services/vpc/models/VpcList.ts
Labels: ncloud-sdk

#24 Verdaccio 테스트 자동화 스크립트 작성
  .gitignore
  package.json
  packages/cli/.npmrc
  packages/cli/CHANGELOG.md
  packages/cli/package.json
  packages/ncloud-sdk/package.json
  scripts/verdaccio-publish/index.sh
Labels: project setup

#25 [Client#1] - Pan Zoom 구현
  packages/client/src/App.tsx
  packages/client/src/components/Background/LinePattern.tsx
  packages/client/src/components/Background/SubLinePattern.tsx
  packages/client/src/components/Background/index.tsx
  packages/client/src/components/CanvasFlow/index.tsx
  packages/client/src/hooks/useZoomPan.ts
  packages/client/src/main.tsx
  packages/client/tsconfig.json
Labels: client

#27 NCloud SDK - Subnet 마이그레이션
  packages/ncloud-sdk/src/services/subnet/SubnetApi.ts
  packages/ncloud-sdk/src/services/subnet/models/CommonCode.ts
  packages/ncloud-sdk/src/services/subnet/models/CreateSubnetRequest.ts
  packages/ncloud-sdk/src/services/subnet/models/CreateSubnetResponse.ts
  packages/ncloud-sdk/src/services/subnet/models/DeleteSubnetRequest.ts
  packages/ncloud-sdk/src/services/subnet/models/DeleteSubnetResponse.ts
  packages/ncloud-sdk/src/services/subnet/models/GetSubnetDetailRequest.ts
  packages/ncloud-sdk/src/services/subnet/models/GetSubnetDetailResponse.ts
  packages/ncloud-sdk/src/services/subnet/models/GetSubnetListRequest.ts
  packages/ncloud-sdk/src/services/subnet/models/GetSubnetListResponse.ts
  packages/ncloud-sdk/src/services/subnet/models/NcloudResponse.ts
  packages/ncloud-sdk/src/services/subnet/models/Subnet.ts
  packages/ncloud-sdk/src/services/subnet/models/SubnetList.ts
  packages/ncloud-sdk/src/services/subnet/models/SubnetNoList.ts
Labels: ncloud-sdk

#52 Edge 구부리는 기능 구현
  apps/client/mocks/instance.ts
  apps/client/package-lock.json
  apps/client/src/cloudflow/components/Anchor/index.tsx
  apps/client/src/cloudflow/components/Background/index.tsx
  apps/client/src/cloudflow/components/Edge/index.tsx
  apps/client/src/cloudflow/components/Flow/index.tsx
  apps/client/src/cloudflow/components/Node/CloudNode/Server.tsx
  apps/client/src/cloudflow/components/Node/CloudNode/index.tsx
  apps/client/src/cloudflow/components/Node/CommonNode/Pointer.tsx
  apps/client/src/cloudflow/components/Node/CommonNode/index.tsx
  apps/client/src/cloudflow/components/Node/index.tsx
  apps/client/src/cloudflow/constants/index.ts
  apps/client/src/cloudflow/contexts/EdgeContext/index.tsx
  apps/client/src/cloudflow/contexts/EdgeContext/reducer.ts
  apps/client/src/cloudflow/hooks/useConnection.ts
  apps/client/src/cloudflow/hooks/useDragNode.ts
  apps/client/src/cloudflow/hooks/useMocks.ts
  apps/client/src/cloudflow/hooks/useSplitEdge.ts
  apps/client/src/cloudflow/hooks/useVisible.ts
  apps/client/src/cloudflow/index.tsx
  apps/client/src/cloudflow/types/index.ts
  apps/client/src/cloudflow/utils/index.ts
  apps/client/src/theme/index.ts
  pnpm-lock.yaml
Labels: client

#48 public architecture, star, import API 구현
  apps/server/prisma/schema/public-architecture.prisma
  apps/server/src/architecture/public-import/dto/create-public-import.dto.ts
  apps/server/src/architecture/public-import/dto/update-public-import.dto.ts
  apps/server/src/architecture/public-import/entities/public-import.entity.ts
  apps/server/src/architecture/public-import/public-import.controller.ts
  apps/server/src/architecture/public-import/public-import.module.ts
  apps/server/src/architecture/public-import/public-import.repository.ts
  apps/server/src/architecture/public-import/public-import.service.ts
  apps/server/src/architecture/public-star/dto/create-public-star.dto.ts
  apps/server/src/architecture/public-star/dto/update-public-star.dto.ts
  apps/server/src/architecture/public-star/entities/public-star.entity.ts
  apps/server/src/architecture/public-star/public-star.controller.ts
  apps/server/src/architecture/public-star/public-star.module.ts
  apps/server/src/architecture/public-star/public-star.repository.ts
  apps/server/src/architecture/public-star/public-star.service.ts
  apps/server/src/architecture/public/dto/create-public.dto.ts
  apps/server/src/architecture/public/dto/update-public.dto.ts
  apps/server/src/architecture/public/entities/public.entity.ts
  apps/server/src/architecture/public/public.controller.spec.ts
  apps/server/src/architecture/public/public.controller.ts
  apps/server/src/architecture/public/public.module.ts
  apps/server/src/architecture/public/public.repository.ts
  apps/server/src/architecture/public/public.service.spec.ts
  apps/server/src/architecture/public/public.service.ts
  apps/server/src/prisma/prisma.module.ts
Labels: server

#53 client/server Dockerfile 세팅
  .dockerignore
  apps/client/Dockerfile
  apps/nginx/nginx.conf
  apps/server/.gitignore
  apps/server/Dockerfile
  apps/server/package.json
  apps/server/prisma/schema/schema.prisma
  pnpm-lock.yaml
Labels: project setup

#56 #1 Edge 삭제 기능
  apps/client/mocks/instance.ts
  apps/client/src/cloudflow/contexts/EdgeContext/reducer.ts
  apps/client/src/cloudflow/contexts/NodeContext/reducer.ts
  apps/client/src/cloudflow/index.tsx
Labels: client

#61 3D Svg
  apps/client/mocks/instance.ts
  apps/client/src/cloudflow/components/Flow/index.tsx
  apps/client/src/cloudflow/contexts/FlowCotext/index.tsx
  apps/client/src/cloudflow/contexts/NodeContext/reducer.ts
  apps/client/src/cloudflow/hooks/useDragNode.ts
  apps/client/src/cloudflow/hooks/useMocks.ts
  apps/client/src/cloudflow/index.tsx
  apps/client/src/cloudflow/utils/index.ts
Labels: client

#70 도커 컴포즈 스크립트 작성
  apps/server/Dockerfile
  config/mysql/init.sql
  config/mysql/log.cnf
  config/prometheus/prometheus.yml
  docker-composes/cloud-canvas-dev.yml
  docker-composes/logging/fluentd/Dockerfile
  docker-composes/logging/fluentd/conf/fluent.conf
  docker-composes/monitoring/database-resource-monitoring-dev.yml
Labels: project setup

#72 Public Architecture(start, import) 테스트 코드 구현
  apps/server/src/architecture/public-import/public-import.controller.spec.ts
  apps/server/src/architecture/public-import/public-import.service.spec.ts
  apps/server/src/architecture/public-import/test/public-import.controller.spec.ts
  apps/server/src/architecture/public-import/test/public-import.service.spec.ts
  apps/server/src/architecture/public-star/public-star.controller.spec.ts
  apps/server/src/architecture/public-star/public-star.controller.ts
  apps/server/src/architecture/public-star/public-star.repository.ts
  apps/server/src/architecture/public-star/public-star.service.spec.ts
  apps/server/src/architecture/public-star/public-star.service.ts
  apps/server/src/architecture/public-star/test/public-star.controller.spec.ts
  apps/server/src/architecture/public-star/test/public-star.service.spec.ts
  apps/server/src/architecture/public/public.controller.spec.ts
  apps/server/src/architecture/public/public.service.spec.ts
  apps/server/src/architecture/public/test/public.controller.spec.ts
  apps/server/src/architecture/public/test/public.service.spec.ts
Labels: server

#79 terraform으로 인프라 선언적 관리
  infra/.gitignore
  infra/dev/main.tf
  infra/init.tf
  infra/modules/server/main.tf
  infra/modules/server/outputs.tf
  infra/modules/server/variables.tf
  infra/modules/vpc_subnet/main.tf
  infra/modules/vpc_subnet/outputs.tf
  infra/modules/vpc_subnet/variables.tf
  infra/prod/main.tf
  infra/variables.tf
Labels: project setup

#88 Feature/mysql dummy
  .github/ISSUE_TEMPLATE/기능-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/리팩토링-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/버그-이슈-템플릿.md
  .github/pull_request_template.md
  .github/workflows/check-open-prs.yml
  .github/workflows/client-ci.yml
  .github/workflows/server-ci.yml
  .husky/pre-commit
  README.md
  apps/server/.eslintrc.js
  apps/server/README.md
  apps/server/nest-cli.json
  apps/server/src/architecture/public-import/dto/create-public-import.dto.ts
  apps/server/src/architecture/public-import/public-import.controller.ts
  apps/server/src/architecture/public-import/public-import.module.ts
  apps/server/src/architecture/public-import/public-import.repository.ts
  apps/server/src/architecture/public-import/public-import.service.ts
  apps/server/src/architecture/public-star/public-star.controller.ts
  apps/server/src/architecture/public-star/public-star.module.ts
  apps/server/src/architecture/public-star/public-star.repository.ts
  apps/server/src/architecture/public-star/public-star.service.ts
  apps/server/src/architecture/public/dto/create-public.dto.ts
  apps/server/src/architecture/public/dto/update-public.dto.ts
  apps/server/src/architecture/public/public.controller.ts
  apps/server/src/architecture/public/public.module.ts
  apps/server/src/architecture/public/public.repository.ts
  apps/server/src/architecture/public/public.service.ts
  apps/server/src/architecture/public/test/public.service.spec.ts
  apps/server/src/prisma/prisma.module.ts
  apps/server/test/app.e2e-spec.ts
  apps/server/tsconfig.build.json
  apps/server/tsconfig.json
  apps/server/vitest.config.e2e.ts
  apps/server/vitest.config.ts
  config/prometheus/prometheus.yml
  docker-composes/cloud-canvas-dev.yml
  docker-composes/monitoring/database-resource-monitoring-dev.yml
  package.json
  packages/ncloud-sdk/src/services/vpc/VpcApi.ts
  packages/ncloud-sdk/src/services/vserver/VserverApi.ts
  packages/ncloud-sdk/src/services/vserver/VserverApiClient.ts
  pnpm-lock.yaml
Labels: server, not completed

#123 허브 페이지 레이아웃
  apps/hub/.eslintrc.json
  apps/hub/.gitignore
  apps/hub/README.md
  apps/hub/next.config.ts
  apps/hub/package.json
  apps/hub/postcss.config.mjs
  apps/hub/src/app/architectures/[id]/page.tsx
  apps/hub/src/app/canvas/page.tsx
  apps/hub/src/app/globals.css
  apps/hub/src/app/layout.tsx
  apps/hub/src/app/login/page.tsx
  apps/hub/src/app/my/architectures/page.tsx
  apps/hub/src/app/my/layout.tsx
  apps/hub/src/app/my/shared/page.tsx
  apps/hub/src/app/my/starred/page.tsx
  apps/hub/src/app/my/withdrawal/page.tsx
  apps/hub/src/app/page.tsx
  apps/hub/src/components/Architectures/header.tsx
  apps/hub/src/components/Architectures/index.tsx
  apps/hub/src/components/Architectures/item.tsx
  apps/hub/src/components/Button.tsx
  apps/hub/src/components/GlobalHeader.tsx
  apps/hub/src/components/LinkButton.tsx
  apps/hub/src/components/MyPageSidebar/index.tsx
  apps/hub/src/components/MyPageSidebar/item.tsx
  apps/hub/src/components/Pagination/LeftArrowIcon.tsx
  apps/hub/src/components/Pagination/RightArrowIcon.tsx
  apps/hub/src/components/Pagination/index.tsx
  apps/hub/src/components/SearchBar/SearchIcon.tsx
  apps/hub/src/components/SearchBar/index.tsx
  apps/hub/src/components/Tag.tsx
  apps/hub/tailwind.config.ts
  apps/hub/tsconfig.json
  package.json
  pnpm-lock.yaml
Labels: client

#124 Docker-compose dev 스크립트 설정
  docker-composes/cloud-canvas-dev.yml
Labels: project setup

#125 ncloud 서버에서의 데이터베이스 마이그레이션을 위한 prisma/migrations 추가
  apps/server/.gitignore
  apps/server/prisma/migrations/20241120062624_/migration.sql
  apps/server/prisma/migrations/migration_lock.toml
  pnpm-lock.yaml
Labels: bug

#127 🚚 Setting(docker-composes): ncloud 인스턴스에서도 도커 컴포즈 실행할 수 있게 스크립트 수정
  .github/workflows/ci-cd.yml
  .github/workflows/client-ci.yml
  docker-composes/cloud-canvas-dev.yml
Labels: project setup

#129 서버 배포 액션 스크립트 버그 수정
  .github/workflows/ci-cd.yml
Labels: project setup

#130 깃허브 액션 SSH 로그인 버그 수정(미완)
  .github/workflows/ci-cd.yml
Labels: bug

#131 깃허브 액션 자동 배포 기능 추가(미완)
  .github/workflows/ci-cd.yml
Labels: project setup

#133 NCloud Terraform 변환 코드 구현
  apps/terraform/convertor/TerraformConvertor.ts
  apps/terraform/enum/ResourcePriority.ts
  apps/terraform/interface/ACG.ts
  apps/terraform/interface/ACGRule.ts
  apps/terraform/interface/CloudCanvasNode.ts
  apps/terraform/interface/FileOption.ts
  apps/terraform/interface/NCloudModel.ts
  apps/terraform/interface/NetworkACL.ts
  apps/terraform/interface/NetworkInterface.ts
  apps/terraform/interface/Provider.ts
  apps/terraform/interface/PublicIp.ts
  apps/terraform/interface/Server.ts
  apps/terraform/interface/Subnet.ts
  apps/terraform/interface/VPC.ts
  apps/terraform/main.ts
  apps/terraform/model/NCloudACG.ts
  apps/terraform/model/NCloudACGRule.ts
  apps/terraform/model/NCloudLoginKey.ts
  apps/terraform/model/NCloudNetworkACL.ts
  apps/terraform/model/NCloudNetworkInterface.ts
  apps/terraform/model/NCloudProvider.ts
  apps/terraform/model/NCloudPublicIP.ts
  apps/terraform/model/NCloudServer.ts
  apps/terraform/model/NCloudSubnet.ts
  apps/terraform/model/NCloudVPC.ts
  apps/terraform/outputs.tf
  apps/terraform/sample/sampleData.ts
  apps/terraform/terraform.tfvars
  apps/terraform/type/ResourceManager.ts
  apps/terraform/type/TerraformGenerator.ts
  apps/terraform/util/file.ts
  apps/terraform/util/formatter.ts
  apps/terraform/util/generator.ts
  apps/terraform/util/reference.ts
  apps/terraform/util/resourceParser.ts
Labels: server, emergency

#139 깃허브 액션 테스트
  README.md
  apps/server/src/app.controller.ts
  pnpm-lock.yaml
Labels: bug

#144 Feature/terraform
  config/mysql/init.sql
  docker-composes/cloud-canvas-back.yml
  docker-composes/database/database-efk.yml
  docker-composes/database/database.yml
  docker-composes/monitoring/resource/docker-compose.yml
Labels: project setup

#150 PR에 빌드 테스트를 진행하는 깃허브 액션 스크립트 추가
  .github/workflows/pr-build-test.yml
Labels: project setup

#153 Ncloud 서버 리소스 가격 조회 배치 기능 구현
  apps/server/prisma/migrations/20241128085427_/migration.sql
  apps/server/prisma/migrations/migration_lock.toml
  apps/server/prisma/schema/ncloud-server-resoruce.prisma
  apps/server/src/main.ts
  apps/server/src/ncloud-resources/ncloud-resources.service.ts
Labels: server

#156 LoadBalancer, MySQL 모델 리팩토링 및 ObjectStroage, Redis 모델 파싱 추가
  packages/terraform/converter/TerraformConverter.ts
  packages/terraform/enum/ResourcePriority.ts
  packages/terraform/interface/ACG.ts
  packages/terraform/interface/LaunchConfiguration.ts
  packages/terraform/interface/LoadBalancer.ts
  packages/terraform/interface/LoginKey.ts
  packages/terraform/interface/NetworkACL.ts
  packages/terraform/interface/NetworkInterface.ts
  packages/terraform/interface/ObjectStorageBucket.ts
  packages/terraform/interface/PublicIp.ts
  packages/terraform/interface/Redis.ts
  packages/terraform/interface/RedisConfigGroup.ts
  packages/terraform/interface/Server.ts
  packages/terraform/interface/Subnet.ts
  packages/terraform/interface/VPC.ts
  packages/terraform/main.ts
  packages/terraform/model/NCloudACG.ts
  packages/terraform/model/NCloudACGRule.ts
  packages/terraform/model/NCloudLaunchConfiguration.ts
  packages/terraform/model/NCloudLoadBalancer.ts
  packages/terraform/model/NCloudLoginKey.ts
  packages/terraform/model/NCloudMySQL.ts
  packages/terraform/model/NCloudNetworkACL.ts
  packages/terraform/model/NCloudNetworkInterface.ts
  packages/terraform/model/NCloudObjectStorageBucket.ts
  packages/terraform/model/NCloudProvider.ts
  packages/terraform/model/NCloudPublicIP.ts
  packages/terraform/model/NCloudRedis.ts
  packages/terraform/model/NCloudRedisConfigGroup.ts
  packages/terraform/model/NCloudServer.ts
  packages/terraform/model/NCloudSubnet.ts
  packages/terraform/model/NCloudVPC.ts
  packages/terraform/test/TerraformConverter.spec.ts
  packages/terraform/util/dependency.ts
  packages/terraform/util/resource.ts
  packages/terraform/util/resourceParser.ts
Labels: terraform-translaction

#162 도커 스크립트 빌드 오류 수정 및 허브 이미지 업로드 기능 추가
  .github/workflows/ci-cd.yml
  apps/client/Dockerfile
  docker-composes/cloud-canvas-local.yml
Labels: bug, project setup

#163 깃허브 액션 스크립트 프론트 이미지 파일 경로 잘못 참조된 것 수정
  .github/workflows/ci-cd.yml
Labels: bug, project setup

#165 도커 컴포즈 백엔드 서버 실행 안되는 버그 수정
  docker-composes/cloud-canvas-back.yml
  docker-composes/cloud-canvas-front-hub.yml
Labels: bug, project setup

#166 back url 못 가져오는 버그 임시 수정
  apps/hub/Dockerfile
  apps/hub/next.config.ts
  apps/hub/src/app/architectures/[id]/page.tsx
  apps/hub/src/app/my/architectures/page.tsx
  apps/hub/src/app/my/shared/page.tsx
  apps/hub/src/app/my/starred/page.tsx
  apps/hub/src/app/page.tsx
  apps/hub/src/components/GlobalHeader/index.tsx
  docker-composes/cloud-canvas-front-hub.yml
Labels: bug, client

#167 cors 에러 수정
  apps/server/src/main.ts
Labels: bug, server
