Repository boostcampwm-2024/web37-cloud-canvas, pull requests merged in 2024-12, with the labels that each got.

#172 terraform server 모듈에서 서버에 관한 아웃풋 추가
  infra/modules/server/outputs.tf
  infra/modules/vpc_subnet/outputs.tf
Labels: project setup

#173 최종 발표를 위한 README 꾸미기
  README.md
  apps/server/src/main.ts
  docker-composes/cloud-canvas-local.yml
Labels: documentation

#184 Feature/convert terraform
  packages/terraform/enum/ResourcePriority.ts
  packages/terraform/interface/KsCluster.ts
  packages/terraform/model/NCloudNKsCluster.ts
  packages/terraform/type/ResourceManager.ts
  packages/terraform/util/dependency.ts
  packages/terraform/util/resource.ts
  packages/terraform/util/resourceParser.ts
Labels: terraform-translaction

#187 깃허브 액션 클라이언트 버그 수정
  .gitignore
  apps/client/.env.development
  apps/client/.env.production
  apps/client/Dockerfile
  apps/client/package.json
  apps/client/vite.config.ts
  apps/server/prisma/migrations/20241203122318_/migration.sql
  apps/server/prisma/schema/ncloud-server-resoruce.prisma
  apps/server/src/app.module.ts
  apps/server/src/clouds/clouds.controller.spec.ts
  apps/server/src/clouds/clouds.controller.ts
  apps/server/src/clouds/clouds.module.ts
  apps/server/src/clouds/clouds.service.spec.ts
  apps/server/src/clouds/clouds.service.ts
  apps/server/src/ncloud-resources/ncloud-resources.service.ts
  docker-composes/cloud-canvas-local.yml
  packages/terraform/interface/CloudCanvasNode.ts
  packages/terraform/util/resource.ts
  pnpm-lock.yaml
Labels: bug

#191 서버에서 가격 계산 기능 추가
  apps/server/src/app.module.ts
  apps/server/src/cloud/cloud.controller.spec.ts
  apps/server/src/cloud/cloud.controller.ts
  apps/server/src/cloud/cloud.module.ts
  apps/server/src/cloud/cloud.service.spec.ts
  apps/server/src/cloud/cloud.service.ts
  apps/server/src/clouds/clouds.controller.ts
  apps/server/src/clouds/clouds.module.ts
  apps/server/src/clouds/clouds.service.ts
  apps/server/src/ncloud-resource/ncloud-resource.service.spec.ts
  apps/server/src/ncloud-resource/ncloud-resource.service.ts
  apps/server/src/private-architecture/private-architecture.module.ts
  apps/server/src/private-architecture/private-architecture.service.ts
  apps/server/src/public-architecture/public-architecture.module.ts
  apps/server/src/public-architecture/public-architecture.service.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: server

#194 Fix/client/last
  apps/client/src/Root.tsx
  apps/client/src/components/CloudGraphProvider.tsx
  apps/client/src/components/NCloud/NetworksBar/RegionSelect.tsx
  apps/client/src/components/SaveDialog.tsx
  apps/client/src/models/ncloud/ImageBlock.ts
  apps/hub/Dockerfile
  apps/hub/public/JP.svg
  apps/hub/public/KR.svg
  apps/hub/public/SG.svg
  apps/hub/public/upload.svg
  apps/hub/src/app/architectures/[id]/page.tsx
  apps/hub/src/components/ArchitectureBoard/ArchitectureItem.tsx
Labels: bug

#197 리소스타입이 달라도 이름 중복이 안되는 문제 해결
  packages/terraform/type/ResourceManager.ts
Labels: terraform-translaction

#190 README 최종 완성
  README.md
Labels: documentation
